# Generated by Django 5.1.7 on 2025-04-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='expertise',
            field=models.CharField(choices=[('OIL_CHANGE', 'Oil Change'), ('ENGINE_REPAIR', 'Engine Repair'), ('TIRE_REPLACEMENT', 'Tire Replacement'), ('BRAKE_SERVICE', 'Brake Service'), ('GENERAL_CHECKUP', 'General Checkup')], max_length=100),
        ),
    ]
