# Generated by Django 5.1.7 on 2025-04-06 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('OIL_CHANGE', 'Oil Change'), ('ENGINE_REPAIR', 'Engine Repair'), ('TIRE_REPLACEMENT', 'Tire Replacement'), ('BRAKE_SERVICE', 'Brake Service'), ('GENERAL_CHECKUP', 'General Checkup')], default='GENERAL_CHECKUP', max_length=50)),
                ('preferred_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
