# Generated by Django 5.1.7 on 2025-04-15 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer'),
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to='service_provider.serviceprovider'),
        ),
    ]
