# Generated by Django 5.1.7 on 2025-04-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_assigned_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
