# Generated by Django 5.1.7 on 2025-04-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_servicebooking_status'),
        ('service_provider', '0002_alter_serviceprovider_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_provider.serviceprovider'),
        ),
    ]
